### ISSUE TITLE
User can create a todo.

### ISSUE THREAD

**Issue by riley-rangel** [riley-rangel/continuous-delivery#9]
# Motivation
Users will want to store new todos.

# Implementation
- [x] Restructure project directory.
- [x] Define and test a gateway method that can save and return a `todo`.
- [x] Define and test a `POST` route that can store and respond with a `todo`.
- [x] Add any missing linter configurations.
- [x] Install `react` and accompanying dependencies.
- [x] Ensure that client JavaScript files are bundled into the server's `public/` directory.
- [x] Add static middleware to server.
- [x] Define a `TodoForm` component that can `POST` a new `todo` to the server route, styled with Bootstrap, Materialize, Foundation, or Semantic UI.
- [x] Ensure that the `NPM_CONFIG_PRODUCTION` environment variable is set to `false` on Heroku.
- [x] Add a `heroku-postbuild` NPM script that bundles the client JavaScript.
